### ISSUE TITLE
"Impossible cron expression" thrown on timezones that offsets with minuets 

### ISSUE THREAD

**Issue by manchuck** [mtdowling/cron-expression#91] opened 2015-05-11 18:38 UTC
for time zones that have an offset with minuets, an "Impossible cron expression is thrown when calling isDue or getNextRunDate.  It appears to happen because the getNextRun date keeps adding hours and then hits a limit in a for loop.  

Steps
----

1. use the following expression: 0 */5 * * * *
2. Set time zone to one that has offset with minuets (Asia/Kabul, or Asia/Calcutta)
3. Call next getNextRunDate(null, 0, true);

Expected
-----

The next run date for the job is returned

Actual
-----

An Exception is thrown with the message "Impossible cron expression"

**Comment by mtdowling** [comment] 2015-05-11 18:47
Can you explain what you mean by "Set time zone to one that has offset with minuets (Asia/Kabul, or Asia/Calcutta)"? Are these time zones different than other time zones in that they are GMT +XX:YY?

**Comment by manchuck** [comment] 2015-06-03 14:47
@mtdowling Asia/Kabul has an UTC offset of +04:30.  When getRunDate tries to figure out when the next time to run is going to be. It looses the 30 min and keeps looping then fails.  I have confirmed that this happens with all TZ that have offset with min.

**Comment by Rob6566** [comment] 2015-08-11 06:14
I've encountered this problem too. All timezones with a minute offset (eg: Australia/Adelaide +0930) are looping 1000 times in getRunDate then returning "Impossible CRON expression".

**Comment by Rob6566** [comment] 2015-08-11 07:25
I think the problem is in HoursField.php. Currently it converts to UTC, jumps to the start/end of the hour, then converts back (ending up in the middle of the hour, if the timezone is XX:30).

This code probably needs some more testing, but is working for me:

In HoursField.php, around line 22
------------------------------
FIND
------------------------------

        if ($invert) {
            $date->modify('-1 hour');
            $date->setTime($date->format('H'), 59);
        } else {
            $date->modify('+1 hour');
            $date->setTime($date->format('H'), 0);
        }
        $date->setTimezone($timezone);

------------------------------
REPLACE WITH
------------------------------
       $date->setTimezone(new \DateTimeZone('UTC'));
        if ($invert) {
            $date->modify('-1 hour');
            $date->setTimezone($timezone);
            $date->setTime($date->format('H'), 59);
        } else {
            $date->modify('+1 hour');
            $date->setTimezone($timezone);
            $date->setTime($date->format('H'), 0);
        }

**Comment by dragonmantank** [comment] 2016-01-26 22:04
This should now be fixed in v1.1.0. 

If not, feel free to re-open this issue.

**Closed by dragonmantank** 2016-01-26 22:04 UTC
